name: "Build and Push to Google Artifactory"
description: "Build a docker container and publish it to Google Artifactory."
inputs:
  google-key:
    description: "Key to authenticate gcloud"
    required: true
  service-name:
    description: "service name"
    required: true
  google-project:
    description: "GCP project to use"
    required: false
    default: "tilda-dev-325721"
  context:
    description: "Path to the docker context"
    required: false
    default: .
  file:
    description: "Path to Dockerfile"
    required: false
    default: Dockerfile
  push:
    description: "Whether to push the image to artifactory or not"
    required: false
    type: boolean
    default: true
  artifactory-url:
    description: "url"
    required: false
    default: us-central1-docker.pkg.dev
  target:
    description: "Sets the target stage to build"
    required: false
  build_args:
    description: 'Additional build arguments as a string'
    required: false
  merge-into:
    description: 'Branch to merge into before building'
    required: false
    default: 'main'
outputs:
  image:
    description: "Build docker image"
    value: ${{ steps.meta.outputs.tags }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        fetch-depth: 0

    - name: Merge into specified branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin ${{ inputs.merge-into }}
        git checkout ${{ inputs.merge-into }}
        git merge ${{ github.sha }} --no-ff -m "Merge ${{ github.ref }} into ${{ inputs.merge-into }} for build"
      shell: bash

    - name: Repo Name
      id: repo-name
      uses: frabert/replace-string-action@v2.0
      with:
        string: ${{ github.repository }}
        pattern: ${{ github.repository_owner }}/
        replace-with: ""

    - uses: google-github-actions/auth@v1
      if: github.event.pull_request.user.login != 'dependabot[bot]'
      with:
        credentials_json: ${{ inputs.google-key }}

    - uses: google-github-actions/setup-gcloud@v1

    - run: gcloud auth configure-docker ${{ inputs.artifactory-url }}
      shell: bash

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.artifactory-url }}/${{ inputs.google-project }}/artifacts/services/${{ inputs.service-name }}
        tags: |
          type=sha,enable=true,priority=100,prefix=${{ github.head_ref || github.ref_name}}-,suffix=,format=short

    - uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        target: ${{ inputs.target }}
        build-args: |
          BUILDARG_VERSION=${{ steps.meta.outputs.version }}
          ${{ inputs.build_args }}

    - run: echo ${{ steps.meta.outputs.tags }} >> $GITHUB_STEP_SUMMARY
      shell: bash