name: 'Validate PR Title'
description: 'Validates PR title starts with ENG-XXXX format (e.g., ENG-1234)'
author: 'Tilda Bio'

inputs:
  pr-title:
    description: 'The PR title to validate'
    required: true
  github-token:
    description: 'GitHub token for posting comments'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  pr-user:
    description: 'Pull request author username'
    required: true
  repository:
    description: 'Repository name in format owner/repo'
    required: true

outputs:
  validation-status:
    description: 'Validation result: valid or invalid'
    value: ${{ steps.validation.outputs.validation_status }}

runs:
  using: 'composite'
  steps:
    - name: Validate PR title format
      id: validation
      shell: bash
      env:
        PR_TITLE: ${{ inputs.pr-title }}
        PR_USER: ${{ inputs.pr-user }}
        PR_NUMBER: ${{ inputs.pr-number }}
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Validating PR title: $PR_TITLE"

        if [[ "$PR_TITLE" =~ ^ENG-[0-9]+ ]]; then
          echo "validation_status=valid" >> $GITHUB_OUTPUT
          echo "PR title is valid: starts with ${BASH_REMATCH[0]}"
        else
          echo "validation_status=invalid" >> $GITHUB_OUTPUT
          echo "ERROR: PR title must start with ENG-XXXX (e.g., ENG-1234)"
          echo ""
          echo "Current title: $PR_TITLE"
          echo ""
          echo "QUICK FIX: Update your PR title to start with a valid ticket ID"
          echo "   Example: ENG-1234 Add new feature"

          # Post comment on PR
          COMMENT="## PR Title Validation Failed

        Hi @${PR_USER}!

        Your PR title does not follow the required format.

        **Current Title:** \`${PR_TITLE}\`

        **Required Format:** PR titles must start with \`ENG-XXXX\` where \`XXXX\` are digits.

        **Examples:**
        - \`ENG-1234 Add user authentication\`
        - \`ENG-5678 Fix login bug\`

        **How to Fix:**
        1. Edit your PR title
        2. Add the ticket ID at the beginning (e.g., \`ENG-1234\`)
        3. The check will automatically re-run"

          gh pr comment "$PR_NUMBER" --repo "$REPOSITORY" --body "$COMMENT" || true

          exit 1
        fi

branding:
  icon: 'edit-3'
  color: 'blue'
