name: Auto Merge
description: Auto approve and merge PRs

# Trigger the workflow on pull request
inputs:
  github-token:
    description: "GitHub token with repo permissions"
    required: false
  github-ci-bot-pat:
    description: "GitHub PAT for the ci-bot"
    required: false
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.github-token }}
      uses: hmarr/auto-approve-action@v2.1.0 # Custom action for auto approval already available on marketplace
      # Perform the auto approve action only when the PR is raised by dependabot
      with:
        # Create a personal access token and store it under the Secrets section of the particular repository
        # with the key "GITHUB_ACTIONS_TOKEN"
        github-token: ${{ inputs.github-token }}

    - if: ${{ inputs.github-ci-bot-pat }}
      uses: hmarr/auto-approve-action@v2.1.0 # Custom action for auto approval already available on marketplace
      # Perform the auto approve action only when the PR is raised by dependabot
      with:
        # Create a personal access token and store it under the Secrets section of the particular repository
        # with the key "GITHUB_ACTIONS_TOKEN"
        github-token: ${{ inputs.github-ci-bot-pat }}

    - if: ${{ inputs.github-ci-bot-pat || inputs.github-token }}
      # Custom action for auto merging already available on marketplace
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ inputs.github-ci-bot-pat || inputs.github-token }}
